<?php
namespace App\modules\SD\Helper\Facades;
use Illuminate\Support\Facades\Facade;

/**
 * Created by PhpStorm.
 * User: Arafat
 * Date: 6/13/2016
 * Time: 10:52 AM
 */
class DemandConstantFacdes extends Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     *
     * @throws \RuntimeException
     */
    protected static function getFacadeAccessor()
    {
        return 'DemandConstant'; // TODO: Change the autogenerated stub
    }

}