<?php
/**
 * Created by PhpStorm.
 * User: arafat
 * Date: 7/18/2016
 * Time: 5:16 PM
 */

namespace App\Helper\Facades;


use Illuminate\Support\Facades\Facade;

class UserPermissionFacades extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'UserPermission'; // TODO: Change the autogenerated stub
    }


}