<?php
return [
    'title'=>[
        'personal_info'=>['eng'=>'Personal Info','bng'=>'বাক্তিগত ও পারিবারিক তথ্'],
        'permanent_address'=>['eng'=>'Permanent Address','bng'=>'স্থায়ী ঠিকানা'],
        'physical_info'=>['eng'=>'Physical Information','bng'=>'শারীরিক যোগ্যতার তথ্য'],
        'edu_info'=>['eng'=>'Educational Information','bng'=>'শিক্ষাগত যোগ্যতার তথ্য'],
        'train_info'=>['eng'=>'Training Information','bng'=>'প্রশিক্ষন সংক্রান্ত তথ্য্'],
        'nominee_info'=>['eng'=>'Nominee Information','bng'=>'উত্তরাধিকারীর তথ্য'],
        'other_info'=>['eng'=>'Other Information','bng'=>'অন্যান্য তথ্য'],

    ],
    'label'=>[
        'id'=>['eng'=>'ID No.','bng'=>'আইডি নং'],
        'name'=>['eng'=>'Name','bng'=>'নাম'],
        'bd'=>['eng'=>'Birth Date','bng'=>'জন্ম তারিখ'],
        'rank'=>['eng'=>'Rank','bng'=>'পদবী'],
        'mn'=>['eng'=>'Mobile No.','bng'=>'মোবাইল নং'],
        'fn'=>['eng'=>'Father Name','bng'=>'পিতার নাম'],
        'mtn'=>['eng'=>'Mother Name','bng'=>'মাতার নাম'],
        'ms'=>['eng'=>'Maritual Status','bng'=>'বৈবাহিক অবস্থা'],
        'hwn'=>['eng'=>'Husband/Wife Name','bng'=>'স্ত্রী/স্বামীর নাম'],
        'nin'=>['eng'=>'National Id No.','bng'=>'জাতীয় পরিচয়পত্র নং'],
        'bc'=>['eng'=>'Birth Certificate no.','bng'=>'জন্ম নিবন্ধন সনদ নং'],
        'vv'=>['eng'=>'Village','bng'=>'গ্রাম'],
        'po'=>['eng'=>'Post Office','bng'=>'ডাকঘর'],
        'un'=>['eng'=>'Union','bng'=>'ইউনিয়ন'],
        'th'=>['eng'=>'Thana','bng'=>'থানা'],
        'ds'=>['eng'=>'District','bng'=>'জেলা'],
        'dv'=>['eng'=>'Division','bng'=>'বিভাগ'],
        'hh'=>['eng'=>'Height','bng'=>'উচ্চতা'],
        'bcc'=>['eng'=>'Body Color','bng'=>'গায়ের রং'],
        'bg'=>['eng'=>'Blood Group','bng'=>'রক্তের গ্রুপ'],
        'gen'=>['eng'=>'Gender','bng'=>'লিঙ্গ'],
        'ec'=>['eng'=>'Eye Color','bng'=>'চোখের রং'],
        'im'=>['eng'=>'Identification Mark','bng'=>'সনাক্তকরন চিহ্ন'],
        'eq'=>['eng'=>'Education Qualification','bng'=>'শিক্ষাগত যোগ্যতা'],
        'in'=>['eng'=>'Institute Name','bng'=>'শিক্ষা প্রতিষ্ঠানের নাম'],
        'py'=>['eng'=>'Passing Year','bng'=>'পাসের সাল'],
        'dc'=>['eng'=>'Division/Grade','bng'=>'বিভাগ / শ্রেণী'],
        'rel'=>['eng'=>'Relation','bng'=>'সম্পর্ক'],
        'per'=>['eng'=>'Percentage','bng'=>'অংশ(%)'],
        'tin'=>['eng'=>'Institute Name','bng'=>'প্রতিষ্ঠান	'],
        'tsd'=>['eng'=>'Training Starting Date','bng'=>'প্রশিক্ষন শুরুর তারিখ	'],
        'ted'=>['eng'=>'Training Ending Date','bng'=>'প্রশিক্ষন শেষের তারিখ	'],
        'cn'=>['eng'=>'Certificate No.','bng'=>'সনদ নং	'],
    ]
];